### ISSUE TITLE
Getting Lammps Up and Running with Python

### ISSUE THREAD

**Issue by PatrickSJacobs** [conda-forge/lammps-feedstock#111]
### Comment:

Hi! Thank you for taking the time to read my post:

- Is PyLammps accessible via the conda installation of Lammps? 

- I am having some issues, but before I post them, I want to gain a better understanding of what I am doing. Also if I am getting a module load error due to "import lammps", what information would you need from me to help me?

Please respond whenever it is most convenient for you,

Thank you!!!

**Comment by jan-janssen** [comment]
Yes, PyLammps is included and in terms of the error we currently have issues with `2021.10.27` so the latest stable version is `2021.09.29`. But if you can post your error message and the lamps version `conda list lammps` then we should be able to help you.

**Comment by jan-janssen** [comment]
And your operation system, otherwise I assume your are using linux.

**Comment by PatrickSJacobs** [comment]
Good morning! Thank you for your quick reply; I apologize for not replying sooner. I switched my version of Lammps to 2021.09.29 and I am no longer getting the module load error. I am attempting to run, on a **macOS system**, simple.ipynb (.../lammps/python/examples/pylammps/simple.ipynb) but am receiving the error messages printed in the pdf file I attached and am not understanding the reason for them. Any help you would be willing and able to provide would be appreciated. 

Please respond whenever it is most convenient for you.

[simple.pdf](https://github.com/conda-forge/lammps-feedstock/files/8915596/simple.pdf)

**Comment by jan-janssen** [comment]
ok, there are a couple of similar issues on the lammps issue page: 
* https://github.com/lammps/lammps/issues/1039
* https://github.com/lammps/lammps/issues/2380

Trying your example on an Apple M1 Mac I get the same error message. Do you use an Apple M1 or an Intel Mac? I can try the example on a Linux system tomorrow, but I have the feeling it is not related to the conda package but more a general LAMMPS issue.

**Comment by PatrickSJacobs** [comment]
I am using an Intel Mac and I am trying to run my code currently via juptyer.

**Comment by jan-janssen** [comment]
Ok, I now have an intel Mac and get the same error. So I would suggest you open an issue with the Lammps developers, it seems there is something wrong with the pylammps interface.

**Comment by PatrickSJacobs** [comment]
OK, will do! Thank you!

**Comment by akohlmey** [comment]
@jan-janssen Please note that the LAMMPS developers do not have the resources to track down issues that happen with packaged binaries. We generally require that issues can be reproduced with the latest patch release when built from source on a known combination of libraries and compilers that we can access (e.g. via a container). So suggesting to a user of the conda packaged version of LAMMPS to create an issue in the LAMMPS github repo is creating a difficult situation for that user, since people generally use packaged binaries *because* they are not familiar or comfortable with building software from source.

I don't see a simple solution for that currently, I just wanted to raise awareness of the situation.

**Comment by jan-janssen** [comment]
@akohlmey So this issue does not appear for regular builds? I just updated the version to the update 3 for 2021.09.29, maybe this already fixes the issue. I personally usually use the lammps library directly, so I thought it might be a general issue with the `pylammps` interface.

**Comment by jan-janssen** [comment]
@akohlmey @lubbersnick tested a LAMMPS version from 24 Mar 2022 compiled by himself and he gets the same error.

**Comment by akohlmey** [comment]
> @akohlmey @lubbersnick tested a LAMMPS version from 24 Mar 2022 compiled by himself and he gets the same error. 

Was this on MacOS or Linux?
I have tested the current development branch on Linux and I don't see it.

**Comment by akohlmey** [comment]
[simple - Jupyter Notebook.pdf](https://github.com/conda-forge/lammps-feedstock/files/8924394/simple.-.Jupyter.Notebook.pdf)
this was printed to PDF from my webbrowser on my local machine after compiling LAMMPS, then doing "make install-python", change to the "python/examples/pylammps/" folder and executing "jupyter notebook simple.ipynb".

**Comment by lubbersnick** [comment]
> Was this on MacOS or Linux?
> I have tested the current development branch on Linux and I don't see it.

MacOS. The kernel just crashes on the cell that reads `L.image(zoom=1.0)`. Usually when the kernel crashes and no error information emerges on the command line it is a hard crash to the python process such as segfault.

**Comment by akohlmey** [comment]
> MacOS. The kernel just crashes on the cell that reads `L.image(zoom=1.0)`. Usually when the kernel crashes and no error information emerges on the command line it is a hard crash to the python process such as segfault.

Can you please insert a cell before that statement and add the command `L.info('config')`?
This cell can fail because the underlying python code does a `dump image` writing an image in PNG format, but if the PNG and ZLIB development files are not available on the machine, it will not be available. 
The output of the `info config` command should show whether PNG is available.

**Comment by jan-janssen** [comment]
The issue between ipython and Jupyter seems to be:
```
print(get_ipython().__class__.__name__)
``` 
Returns `ZMQInteractiveShell` for Jupyter but `TerminalInteractiveShell` for ipython. And I have the feeling that the `ZMQInteractiveShell` is not compatible to LAMMPS.

**Comment by jan-janssen** [comment]
> @jan-janssen This confuses me, does lammps actually use the value of the shell? It seems more like, that's how to distinguish the two environments programmatically, rather than the exact cause.
There seems to be a fundamental difference in the way how these two shells handle the communication with external codes. We had a similar issue with openbabel in Architector. 

> Does your installation include the PNG linking? Or it's a different issue?
It is a different issue
