### ISSUE TITLE
How to best provide current versions?

### ISSUE THREAD

**Issue by gdonval** [conda-forge/lammps-feedstock#113]
### Comment:

You provide the latest stable version.

Would you be willing to produce a current version as well or should that be in another package?

I believe stable and current versions could be passed as normal variants and could easily appear in the version string for people to select the version they want (it is also pretty easy to default to stable if necessary).

But if you are unwilling, I'll start the procedure to create a new feedstock.

**Comment by jan-janssen** [comment]
I guess it is primarily a time constraint. Currently not all plugins are compatible with the recent changes, but we are working with the developers of the plugins to release a new version as soon as it becomes available https://github.com/conda-forge/lammps-feedstock/pull/109

**Comment by akohlmey** [comment]
@jan-janssen since several external packages seem to be abandoned (for example, I've submitted a merge request to the USER-VCSGC repo and failed to get *any* response, even on a second message directly addressing the repo maintainers), I have started a [lammps-plugins](https://github.com/lammps/lammps-plugins/) repository where those packages exist in updated versions and with the build infrastructure to build them as plugins rather than including them into LAMMPS (which is, of course, possible, too). However, I think the plugin mechanism is advantageous for providing binary packages, as it allows to update the base package independently from the plugin. The plugin repo follows the same branch scheme as the LAMMPS repository (develop, release, stable) and will also have the same tags (patch_3Aug2022 is available now, the stable tag will be applied once the first update for the stable release is published).

**Comment by jan-janssen** [comment]
Hi @akohlmey,

 I tired to build the current stable release and while vcsgc builds fine based on the `lammps-plugins` I have trouble with the `USER-MLIP` package. Not sure if this is related but maybe you can take a quick look: 

```
/home/conda/feedstock_root/build_artifacts/lammps_1660247002653/work/src/USER-MLIP/pair_MLIP.cpp: In member function 'virtual void LAMMPS_NS::PairMLIP::init_style()':
/home/conda/feedstock_root/build_artifacts/lammps_1660247002653/work/src/USER-MLIP/pair_MLIP.cpp:254:33: error: 'int LAMMPS_NS::NeighRequest::half' is protected within this context
  254 |   neighbor->requests[irequest]->half = 0;
      |                                 ^~~~
In file included from /home/conda/feedstock_root/build_artifacts/lammps_1660247002653/work/src/USER-MLIP/pair_MLIP.cpp:32:
/home/conda/feedstock_root/build_artifacts/lammps_1660247002653/work/src/neigh_request.h:55:7: note: declared protected here
   55 |   int half;    // half neigh list (set by default)
      |       ^~~~
/home/conda/feedstock_root/build_artifacts/lammps_1660247002653/work/src/USER-MLIP/pair_MLIP.cpp:255:33: error: 'int LAMMPS_NS::NeighRequest::full' is protected within this context
  255 |   neighbor->requests[irequest]->full = 1;
      |                                 ^~~~
In file included from /home/conda/feedstock_root/build_artifacts/lammps_1660247002653/work/src/USER-MLIP/pair_MLIP.cpp:32:
/home/conda/feedstock_root/build_artifacts/lammps_1660247002653/work/src/neigh_request.h:56:7: note: declared protected here
   56 |   int full;    // full neigh list
      |       ^~~~
make[2]: *** [CMakeFiles/lammps.dir/build.make:11718: CMakeFiles/lammps.dir/home/conda/feedstock_root/build_artifacts/lammps_1660247002653/work/src/USER-MLIP/pair_MLIP.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:173: CMakeFiles/lammps.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

The corresponding pull request https://github.com/conda-forge/lammps-feedstock/pull/117

**Comment by akohlmey** [comment]
@jan-janssen the errors are exactly error that stem from outdated source code. But when I google `USER-MLIP LAMMPS`, I find a [gitlab repo](https://gitlab.com/ashapeev/interface-lammps-mlip-2/-/tree/master/LAMMPS/USER-MLIP) that seems to have been updated just two weeks ago and that code looks compatible with the latest stable version of LAMMPS.

**Comment by akohlmey** [comment]
I have started documenting the required changes ordered by when the change was introduced: https://docs.lammps.org/latest/Developer_updating.html

You probably need the ev_init() change, the neighbor list request change, and the virtual/override change for a full update.

**Comment by akohlmey** [comment]
> The issue with that repo is that it requires MLIP2 which is not open source, while MLIP was. [lammps/lammps-plugins#2](https://github.com/lammps/lammps-plugins/issues/2) I am going to try to patch it for backwards compatibility.

This could still be provided as a plugin depending on what license the pair style interface code it under.

**Comment by jan-janssen** [comment]
> This could still be provided as a plugin depending on what license the pair style interface code it under.

The pairstyle code is under GPL v2 - But it requires a couple of head files to link to the library which are not publicly available https://gitlab.com/jan-janssen/interface-lammps-mlip-2/-/blob/master/LAMMPS/USER-MLIP/pair_MLIP.cpp#L24

**Comment by akohlmey** [comment]
> > This could still be provided as a plugin depending on what license the pair style interface code it under.
> 
> The pairstyle code is under GPL v2 - But it requires a couple of head files to link to the library which are not publicly available https://gitlab.com/jan-janssen/interface-lammps-mlip-2/-/blob/master/LAMMPS/USER-MLIP/pair_MLIP.cpp#L24

Yeah, you'd need a more liberal license like BSD or MIT for the pair style for that.

**Comment by jan-janssen** [comment]
@gdonval and @akohlmey I updated to the latest stable version https://github.com/conda-forge/lammps-feedstock/pull/118
