### ISSUE TITLE
Is the mlip dependency really necessary?

### ISSUE THREAD

**Issue by pmrv** [conda-forge/lammps-feedstock#114]
### Comment:

We are running a custom build executable for the mlip package on our cluster, but are still running the conda lammps as well.  Since this package forces the install of mlip, this causes some issues, as there's two binaries in the PATH of users the conda one seems to take precedence over it sometimes.  

Therefore the question: Is it really necessary to include mlip in the dependencies or could it also be an optional dependency or be removed completely.  Since this package only needs the mlip library interface and not the executable to fit potentials, I would guess that the dependency can be safely dropped.  Or does the library interface reference a shared library from the mlip conda package?

**Comment by jan-janssen** [comment]
> We are running a custom build executable for the mlip package on our cluster, but are still running the conda lammps as well. Since this package forces the install of mlip, this causes some issues, as there's two binaries in the PATH of users the conda one seems to take precedence over it sometimes.

The precedence only depends on the order of the entries in your PATH, so I do not understand why you cannot overwrite it. 

> Therefore the question: Is it really necessary to include mlip in the dependencies or could it also be an optional dependency or be removed completely. Since this package only needs the mlip library interface and not the executable to fit potentials, I would guess that the dependency can be safely dropped. Or does the library interface reference a shared library from the mlip conda package?

I guess there are users who might want to use the conda package to try the `mlip` potential fitting so I am a bit reluctant to remove the executables. What could be possible is splitting the library and the executable into separate packages inside https://github.com/conda-forge/mlip-feedstock/

**Comment by pmrv** [comment]
> > We are running a custom build executable for the mlip package on our cluster, but are still running the conda lammps as well. Since this package forces the install of mlip, this causes some issues, as there's two binaries in the PATH of users the conda one seems to take precedence over it sometimes.
> 
> The precedence only depends on the order of the entries in your PATH, so I do not understand why you cannot overwrite it.

We can overwrite it and we do now.  But it is annoying to have to work around a package that we didn't install and don't need. 

> > Therefore the question: Is it really necessary to include mlip in the dependencies or could it also be an optional dependency or be removed completely. Since this package only needs the mlip library interface and not the executable to fit potentials, I would guess that the dependency can be safely dropped. Or does the library interface reference a shared library from the mlip conda package?
> 
> I guess there are users who might want to use the conda package to try the `mlip` potential fitting so I am a bit reluctant to remove the executables. What could be possible is splitting the library and the executable into separate packages inside https://github.com/conda-forge/mlip-feedstock/

I don't see why those users cannot easily install the `mlip` package from conda into their environment.  pyiron users who want to do so cannot use the old mlip binary anyway.  I did a `ldd lmp_mpi` and cannot make out any dynamic library dependence between the lammps binary and the mlip conda package.  I guess the `mlip` library is linked statically into the lammps executable (that's at least also how it is done for the newer mlip versions).  Therefore the `mlip` dependency could be dropped without any change in the binary or splitting the mlip package up.
