### ISSUE TITLE
Would activating other packages be acceptable ?

### ISSUE THREAD

**Issue by Carreau** [conda-forge/lammps-feedstock#12]
Assuming we can get them to work of course. 

In particular so far i believe RIGID is not enabled, and some users on our HPC system would like others like: kspace, manybody, mc, misc, molecule, reax, replica, rigid and user-reaxc

I haven't checked the exact overlap of what was/was not activated but I believe some are missing. 

If so I'll bee happy to send pull-requests, and work on this.

**Comment by jan-janssen** [comment]
Sure, feel free to send a pull-request so far I use: 

```
-D PKG_ASPHERE=ON 
-DPKG_BODY=ON 
-D PKG_CLASS2=ON 
-D PKG_COLLOID=ON 
-D PKG_COMPRESS=OFF 
-D PKG_CORESHELL=ON 
-D PKG_DIPOLE=ON 
-D PKG_GRANULAR=ON 
-D PKG_KSPACE=ON 
-D PKG_MANYBODY=ON 
-D PKG_MC=ON 
-D PKG_MEAM=ON 
-D PKG_MISC=ON 
-D PKG_MOLECULE=ON 
-D PKG_PERI=ON 
-D PKG_REAX=ON 
-D PKG_REPLICA=ON 
-D PKG_SHOCK=ON 
-D PKG_SNAP=ON 
-D PKG_SRD=ON 
-D PKG_OPT=ON 
-D PKG_KIM=OFF 
-D PKG_GPU=OFF 
-D PKG_KOKKOS=OFF
 -D PKG_MPIIO=OFF 
-D PKG_MSCG=OFF 
-D PKG_LATTE=OFF 
-D PKG_USER-MEAMC=ON 
-D PKG_USER-PHONON=ON 
-D WITH_GZIP=ON
```

**Comment by jan-janssen** [comment]
@Carreau I updated the packages - can you give me some feedback if those changes are sufficient for your needs?

**Comment by Carreau** [comment]
Thanks ! I don't use it personally, I'm helping to manage a cluster, and I found this, which seem easier than to recompile every new version. I'll contact the people I know who are using lammps ans see if it fits their use case.

**Comment by Carreau** [comment]
> I'll contact the people I know who are using lammps ans see if it fits their use case.

Meaning: if it doesn't I can justify spending time to send pull requests :-)
