### ISSUE TITLE
enable shared library for lmp_mpi

### ISSUE THREAD

**Issue by njzjz** [conda-forge/lammps-feedstock#123]
### Comment:

When I use `lmp_mpi` from conda-forge to load my plugin

```lammps
plugin load libdeepmd_lmp.so
```
I got the following error:
```
undefined symbol: _ZTIN9LAMMPS_NS7ComputeE
````

Luckily, I am familiar with LAMMPS, so I realize that `liblammps.so` is not linked to LAMMPS, so I try
```
plugin load liblammps.so
plugin load libdeepmd_lmp.so
```
It does work.

I wonder if we can enable `BUILD_SHARED_LIBS=ON` for `lmp_mpi`, so the plugins can be loaded successfully without manually loading `liblammps.so` and we don't need to build again shared libraries.

**Comment by jan-janssen** [comment]
Sounds like a great idea. Can you open the corresponding pull request?
