### ISSUE TITLE
LAMMPS fails to import with JPEG linker error

### ISSUE THREAD

**Issue by mphoward** [conda-forge/lammps-feedstock#136]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

LAMMPS installed with conda fails to import using the GitHub Actions `ubuntu-latest` image. This occurs for many different python and version configurations. Here are some failed tests:

https://github.com/mphowardlab/relentless/actions/runs/4385936522/jobs/7721516301

An example traceback is:

```
Traceback (most recent call last):
  File "/home/runner/work/relentless/relentless/tests/simulate/test_lammps.py", line 179, in test_minimization
    lmp = relentless.simulate.LAMMPS(
  File "/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/relentless/simulate/lammps.py", line 1303, in __init__
    lmp = lammps.lammps(
  File "/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/lammps/core.py", line 150, in __init__
    self.lib = CDLL(libpath,RTLD_GLOBAL)
  File "/usr/share/miniconda3/envs/test/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libjpeg.so.9: cannot open shared object file: No such file or directory
```

I would guess this is because LAMMPS is autodetecting and linking against a certain JPEG library in the build image that is not present in this run image. A possible solution would be to make a JPEG library a conda build dependency, or to disable the JPEG option.

### Installed packages

```shell
See test configuration:

https://github.com/mphowardlab/relentless/blob/main/.github/workflows/test.yml
```

### Environment info

```shell
See test configuration:

https://github.com/mphowardlab/relentless/blob/main/.github/workflows/test.yml
```

**Comment by jan-janssen** [comment]
I hope this is fixed by explicitly linking to `libjpeg` in https://github.com/conda-forge/lammps-feedstock/pull/137

**Comment by jan-janssen** [comment]
@mphoward  Can you try to update the LAMMPS version and check if that solves your issue?

**Comment by mphoward** [comment]
Thanks for this fix! It worked on this test run:

https://github.com/mphowardlab/relentless/pull/192/checks

(Ignore the failures for 2021.09.29, I forced the build number to make sure I got the new 2022.06.23.)

While you were working on this, I was able to get things running by installing the `libjpeg9` runtime library through `apt`.

**Comment by jan-janssen** [comment]
> While you were working on this, I was able to get things running by installing the `libjpeg9` runtime library through `apt`.

Yes, that is the same we do in https://github.com/conda-forge/lammps-feedstock/pull/137 - thank you for reporting this.
