### ISSUE TITLE
.so files missing from the macos builds.

### ISSUE THREAD

**Issue by Carreau** [conda-forge/lammps-feedstock#2]
you can test by unpacking the linux and macos form [the repository](https://anaconda.org/conda-forge/lammps/files?sort=ndownloads&sort_order=desc), 

The  `.so` is missing. 

I guess that is why the archive is way smaller. we can likely prevent that by adding the `lmp = lammps()` into the test section of meta.yml.

**Comment by Carreau** [comment]
That might be because on OSX the extension is `dylib` ?

**Comment by jan-janssen** [comment]
I opened a pull request on the official Lammps repo: https://github.com/lammps/lammps/pull/1315 and included the corresponding patch in https://github.com/conda-forge/lammps-feedstock/pull/6

**Comment by jan-janssen** [comment]
It is working in:
https://github.com/conda-forge/lammps-feedstock/pull/7
installation testing on travis:
https://travis-ci.org/conda-forge/lammps-feedstock/jobs/487904551#L2042

**Comment by jan-janssen** [comment]
The libraries are now included in the anaconda packages - currently requiring MPICH support. The next step is working on OpenMPI support https://github.com/conda-forge/lammps-feedstock/pull/8 but that is a different topic, so I am going to close this issue.
