### ISSUE TITLE
list availability of conda lammps package to lammps documentaion

### ISSUE THREAD

**Issue by ellio167** [conda-forge/lammps-feedstock#29]
Might be a good idea to submit a PR to https://github.com/lammps/lammps and list this conda package as another source for binary install (both linux and mac).

**Comment by jan-janssen** [comment]
I informed the LAMMPS developers about the conda forge package when I pushed some changes to the python interface. I guess it is up to them to list it to the sources for binaries https://github.com/lammps/lammps/pull/1315#issuecomment-462022580 but if you know some of them personally maybe you can emphasize this point again. I would be very happy to see conda listed as official source and I am always open to add more people as maintainers if they are interested in supporting the conda packaging.

**Comment by ellio167** [comment]
@jan-janssen I'll be happy to join as a maintainer of this repo.  I'll see if I can put together a PR to update the lammps install docs.
