### ISSUE TITLE
Missing main label in conda-forge for 2018.12.12 

### ISSUE THREAD

**Issue by dwhswenson** [conda-forge/lammps-feedstock#5]
The current package (as of #4) isn't labelled with `main` (see https://anaconda.org/conda-forge/lammps/files). Is this intentional? This means that when I run `conda search -c conda-forge lammps`, I only see the old packages:

```
(dev):~ dwhs$ conda search --override -c conda-forge lammps
Loading channels: done
# Name                  Version           Build  Channel
lammps               2018.03.16         mpich_0  conda-forge
lammps               2018.03.16       openmpi_0  conda-forge
lammps               2018.03.16    py27_mpich_0  conda-forge
lammps               2018.03.16  py27_openmpi_0  conda-forge
lammps               2018.03.16    py35_mpich_0  conda-forge
lammps               2018.03.16  py35_openmpi_0  conda-forge
lammps               2018.03.16    py36_mpich_0  conda-forge
lammps               2018.03.16  py36_openmpi_0  conda-forge
```

I'll see the new packages if I look in the `gcc7` label:

```
(dev):~ dwhs$ conda search --override -c conda-forge/label/gcc7 lammps
Loading channels: done
# Name                  Version           Build  Channel
lammps               2018.12.12    py27_mpich_0  conda-forge/label/gcc7
lammps               2018.12.12    py36_mpich_0  conda-forge/label/gcc7
lammps               2018.12.12    py37_mpich_0  conda-forge/label/gcc7
```

Workaround: The following installation should work:

```
conda install -c conda-forge/label/gcc7 lammps
```

(However, after doing that I have the same problem as #2)

**Comment by jan-janssen** [comment]
@dwhswenson - Thanks for testing. 

I have to admit I am still learning about the conda-forge build system and in particular the pinning of mpi. I opened another pull request to move the gcc version to the main label https://github.com/conda-forge/lammps-feedstock/pull/6 as @scopatz pointed out that toolchain is no longer the main compiler and using gcc instead is fine https://github.com/conda-forge/conda-forge.github.io/issues/699 . 

I still have to figure out why the library version for Mac Os is not copied.

**Comment by jan-janssen** [comment]
Seems like an issue with the lammps copying not being operation system independent: 
https://github.com/lammps/lammps/blob/master/python/install.py#L39 - but we should be able to patch that.

**Comment by jan-janssen** [comment]
The main label is added and the Mac Os libraries are now also included, so I am going to close this issue.
