### ISSUE TITLE
USER-PACE licence is incompatible with LAMMPS license

### ISSUE THREAD

**Issue by ellio167** [conda-forge/lammps-feedstock#66]
The inclusion of the USER-PACE package (and distribution of the resulting binary) is a violation of the LAMMPS `GPL-2.0-only` license.

If we want to respect the intent of the LAMMPS developers, we should not include this package.

**Comment by jan-janssen** [comment]
It was merged in https://github.com/lammps/lammps/pull/2699 so I guess we anyway do not need to include it as separate package.

**Comment by ellio167** [comment]
The "-D PKG_USER-PACE=ON" option in `build.sh` causes the PACE code to be downloaded and compiled into lammps.  The resulting binary violates the LAMMPS GPL-2.0-only license and cannot be legally distributed.

There is no fixing this unless PACE changes it's license to GPL-2.0.  Thus, at this time PACE cannot be built into LAMMPS and distributed through conda forge.

**Comment by jan-janssen** [comment]
I just noticed that they changed it recently - somehow I missed that https://github.com/lammps/lammps/commit/9a8ac23663027f319c98ed4a08d4cda55faec606

**Comment by ellio167** [comment]
Yeah, they argue that it's always been GPL-2.0-only, but there were errors in the license file.

See https://github.com/lammps/lammps/issues/2643

**Comment by yury-lysogorskiy** [comment]
Does conda-forge/lammps distribution includes, for example, QUIP package? AFAIK, we have similar "license incompatiblity" situation as in LAMMPS/QUIP package, i.e. QUIP also has  non-GPL2 license.

**Comment by yury-lysogorskiy** [comment]
Also, GPL2-only licensing implies strict limitation on the 3rd party libraries we could use in the development, and since the USER-PACE C++ codebase serves as a core for our ACE ecosystem codebase,  extra limitation  would significantly slow down the development process.  
For example, soon, we are planning to release multispecies implementaiton of ACE (current public USER-PACE is single-specie only), and we are using there yaml-cpp library (MIT license). So, even if we rollback the GPL3 -> GPL2 license for USER-PACE now, the problem will appear again in a short time. That is why we made deliberate choice to distribute USER-PACE as downloadable on the user side library.

**Comment by yury-lysogorskiy** [comment]
I'm not sure if LAMMPS support dynamically linked libraries for pair_styles. Maybe in that case LAMMPS and USER-* packages under non-GPL2 licenses could be distributed separately...

**Comment by ellio167** [comment]
The QUIP package is GPL 2, so I think it is OK.

I think these licensing incompatibility issues are unfortunate, but there seems to be only two choices: follow the licenses or ignore them.  

Because LAMMPS is released under GPL-2.0-only, it is simply not possible to use GPL-3.0-* licensed with it.  The MIT license is GPL compatible, so that shouldn't be a problem, but GPL-3.0 is.

The downloadable library is a good way to go, but it doesn't eliminate the problem if you want to create and distribute prebuilt binaries (like with conda-forge).

**Comment by akohlmey** [comment]
> I'm not sure if LAMMPS support dynamically linked libraries for pair_styles. Maybe in that case LAMMPS and USER-* packages under non-GPL2 licenses could be distributed separately...

Just stumbled across this when reviewing old issues in LAMMPS. Yes, there is a mechanism to dynamically load pair styles (and a few other styles). It was added in the 8 April 2021 version: https://docs.lammps.org/Developer_plugins.html
