### ISSUE TITLE
EXTRA packages in recipe

### ISSUE THREAD

**Issue by srmnitc** [conda-forge/lammps-feedstock#74]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I am skipping the conda environments details, as it is more of a request than a bug. Earlier version had `PKG_USER-MISC` turned on in the conda recipe. A number of fixes and computes present in this package has now moved to `EXTRA-FIX` and `EXTRA-COMPUTE`. Also some pair styles are moved to `EXTRA-PAIR`. Would it possible to turn on these flags by default in the recipe?

More details-
- https://docs.lammps.org/Packages_list.html

Thanks!

**Comment by srmnitc** [comment]
@jan-janssen Thanks!

**Comment by jan-janssen** [comment]
Sure, no problem
